export enum EmailTypes {
  CONFIRM_ACCOUNT = 'CONFIRM_ACCOUNT',
  PASSWORD_RECOVER = 'PASSWORD_RECOVER',
  INVITE_USER = 'INVITE_USER',
}

export enum CustomerTypes {
  COMPANY = 'COMPANY',
  PERSONAL = 'PERSONAL',
}
